openapi: 3.0.0
info:
  title: ProgTalk API
  description: Dokumentacja serwisu społecznościowego dla programistów
  version: 1.0.0
servers:
  - url: https://localhost:3000
    description: Serwer lokalny
