/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    AvatarComponent: typeof import('./src/components/AvatarComponent.vue')['default']
    BaseEmptyState: typeof import('./src/components/shared/BaseEmptyState.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chip: typeof import('primevue/chip')['default']
    ColorPicker: typeof import('primevue/colorpicker')['default']
    CreateTopicDialog: typeof import('./src/components/topics/shared/CreateTopicDialog.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    NavBarComponent: typeof import('./src/components/NavBarComponent.vue')['default']
    Paginator: typeof import('primevue/paginator')['default']
    Password: typeof import('primevue/password')['default']
    ProfileHeader: typeof import('./src/components/profile/ProfileHeader.vue')['default']
    ProfileSettings: typeof import('./src/components/profile/ProfileSettings.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('primevue/skeleton')['default']
    SubtopicsCard: typeof import('./src/components/topics/details/SubtopicsCard.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    TagBadge: typeof import('./src/components/shared/TagBadge.vue')['default']
    TagComponent: typeof import('./src/components/shared/TagComponent.vue')['default']
    TagDialog: typeof import('./src/components/topics/details/TagDialog.vue')['default']
    TagManagementCard: typeof import('./src/components/topics/details/TagManagementCard.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    TopicCard: typeof import('./src/components/topics/general/TopicCard.vue')['default']
    TopicHeader: typeof import('./src/components/topics/details/TopicHeader.vue')['default']
    TopicPost: typeof import('./src/components/topics/details/TopicPost.vue')['default']
    TopicPostList: typeof import('./src/components/topics/details/TopicPostList.vue')['default']
    TopicReplyEditor: typeof import('./src/components/topics/details/TopicReplyEditor.vue')['default']
    TopicStatsCard: typeof import('./src/components/topics/details/TopicStatsCard.vue')['default']
  }
}
